
package com.pilogProperties;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PropertyService", targetNamespace = "http://service.properties.pilog.com/", wsdlLocation = "http://wsrep.pilog.in/PoC/PropertyService?WSDL")
public class PropertyService_Service
    extends Service
{

    private final static URL PROPERTYSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROPERTYSERVICE_EXCEPTION;
    private final static QName PROPERTYSERVICE_QNAME = new QName("http://service.properties.pilog.com/", "PropertyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://wsrep.pilog.in/PoC/PropertyService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROPERTYSERVICE_WSDL_LOCATION = url;
        PROPERTYSERVICE_EXCEPTION = e;
    }

    public PropertyService_Service() {
        super(__getWsdlLocation(), PROPERTYSERVICE_QNAME);
    }

    public PropertyService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROPERTYSERVICE_QNAME, features);
    }

    public PropertyService_Service(URL wsdlLocation) {
        super(wsdlLocation, PROPERTYSERVICE_QNAME);
    }

    public PropertyService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROPERTYSERVICE_QNAME, features);
    }

    public PropertyService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PropertyService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PropertyService
     */
    @WebEndpoint(name = "PropertyServicePort")
    public PropertyService getPropertyServicePort() {
        return super.getPort(new QName("http://service.properties.pilog.com/", "PropertyServicePort"), PropertyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PropertyService
     */
    @WebEndpoint(name = "PropertyServicePort")
    public PropertyService getPropertyServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.properties.pilog.com/", "PropertyServicePort"), PropertyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROPERTYSERVICE_EXCEPTION!= null) {
            throw PROPERTYSERVICE_EXCEPTION;
        }
        return PROPERTYSERVICE_WSDL_LOCATION;
    }

}
