
package com.pilogProperties;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PropertyService", targetNamespace = "http://service.properties.pilog.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PropertyService {


    /**
     * 
     * @param orgnID
     * @param recordNo
     * @return
     *     returns com.pilogProperties.PropertyResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://service.properties.pilog.com/", className = "com.pilogProperties.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://service.properties.pilog.com/", className = "com.pilogProperties.SearchResponse")
    @Action(input = "http://service.properties.pilog.com/PropertyService/searchRequest", output = "http://service.properties.pilog.com/PropertyService/searchResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.properties.pilog.com/PropertyService/search/Fault/Exception")
    })
    public PropertyResponse search(
        @WebParam(name = "recordNo", targetNamespace = "")
        String recordNo,
        @WebParam(name = "ORGN_ID", targetNamespace = "")
        String orgnID)
        throws Exception_Exception
    ;

}
