
package com.pilogParts;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Dictionary/Reference", targetNamespace = "http://service.dictionary.pilog.com/", wsdlLocation = "" +
        "")
public class Dictionary_002fReference
    extends Service
{

    private final static URL DICTIONARY_002FREFERENCE_WSDL_LOCATION;
    private final static WebServiceException DICTIONARY_002FREFERENCE_EXCEPTION;
    private final static QName DICTIONARY_002FREFERENCE_QNAME = new QName("http://service.dictionary.pilog.com/", "Dictionary/Reference");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://wsrep.pilog.in/PoC/Dictionary/Reference?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DICTIONARY_002FREFERENCE_WSDL_LOCATION = url;
        DICTIONARY_002FREFERENCE_EXCEPTION = e;
    }

    public Dictionary_002fReference() {
        super(__getWsdlLocation(), DICTIONARY_002FREFERENCE_QNAME);
    }

    public Dictionary_002fReference(WebServiceFeature... features) {
        super(__getWsdlLocation(), DICTIONARY_002FREFERENCE_QNAME, features);
    }

    public Dictionary_002fReference(URL wsdlLocation) {
        super(wsdlLocation, DICTIONARY_002FREFERENCE_QNAME);
    }

    public Dictionary_002fReference(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DICTIONARY_002FREFERENCE_QNAME, features);
    }

    public Dictionary_002fReference(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dictionary_002fReference(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DictionaryReference
     */
    @WebEndpoint(name = "DictionaryReferencePort")
    public DictionaryReference getDictionaryReferencePort() {
        return super.getPort(new QName("http://service.dictionary.pilog.com/", "DictionaryReferencePort"), DictionaryReference.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DictionaryReference
     */
    @WebEndpoint(name = "DictionaryReferencePort")
    public DictionaryReference getDictionaryReferencePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.dictionary.pilog.com/", "DictionaryReferencePort"), DictionaryReference.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DICTIONARY_002FREFERENCE_EXCEPTION!= null) {
            throw DICTIONARY_002FREFERENCE_EXCEPTION;
        }
        return DICTIONARY_002FREFERENCE_WSDL_LOCATION;
    }

}
