
package com.pilogParts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DictionaryReference", targetNamespace = "http://service.dictionary.pilog.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DictionaryReference {


    /**
     * 
     * @param request
     * @return
     *     returns com.pilogParts.ReferenceResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchReference", targetNamespace = "http://service.dictionary.pilog.com/", className = "com.pilogParts.SearchReference")
    @ResponseWrapper(localName = "searchReferenceResponse", targetNamespace = "http://service.dictionary.pilog.com/", className = "com.pilogParts.SearchReferenceResponse")
    @Action(input = "http://service.dictionary.pilog.com/DictionaryReference/searchReferenceRequest", output = "http://service.dictionary.pilog.com/DictionaryReference/searchReferenceResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.dictionary.pilog.com/DictionaryReference/searchReference/Fault/Exception")
    })
    public ReferenceResponse searchReference(
        @WebParam(name = "request", targetNamespace = "")
        ReferenceRequest request)
        throws Exception_Exception
    ;

}
